#include "CountryDatabase.h"

std::map<std::string, std::string> CountryDatabase::getCountryData()
{
    return {
        {"France", "Paris"},
        {"Spain", "Madrid"},
        {"Germany", "Berlin"},
        {"Italy", "Rome"},
        {"Japan", "Tokyo"},
        {"Brazil", "Brasilia"},
        {"India", "New Delhi"},
        {"Canada", "Ottawa"},
        {"Australia", "Canberra"},
        {"Mexico", "Mexico City"},
        {"United States", "Washington, D.C."},
        {"United Kingdom", "London"},
        {"China", "Beijing"},
        {"Russia", "Moscow"},
        {"South Korea", "Seoul"},
        {"South Africa", "Pretoria"},
        {"Argentina", "Buenos Aires"},
        {"Colombia", "Bogotá"},
        {"Peru", "Lima"},
        {"Chile", "Santiago"},
        {"Egypt", "Cairo"},
        {"Saudi Arabia", "Riyadh"},
        {"Turkey", "Ankara"},
        {"Greece", "Athens"},
        {"Netherlands", "Amsterdam"},
        {"Sweden", "Stockholm"},
        {"Norway", "Oslo"},
        {"Denmark", "Copenhagen"},
        {"Poland", "Warsaw"},
        {"Finland", "Helsinki"},
        {"Portugal", "Lisbon"},
        {"Belgium", "Brussels"},
        {"Switzerland", "Bern"},
        {"Austria", "Vienna"},
        {"Czech Republic", "Prague"},
        {"Hungary", "Budapest"},
        {"Thailand", "Bangkok"},
        {"Vietnam", "Hanoi"},
        {"Indonesia", "Jakarta"},
        {"Malaysia", "Kuala Lumpur"},
        {"Philippines", "Manila"},
        {"New Zealand", "Wellington"},
        {"Singapore", "Singapore"},
        {"Pakistan", "Islamabad"},
        {"Bangladesh", "Dhaka"},
        {"Sri Lanka", "Colombo"},
        {"Nigeria", "Abuja"},
        {"Kenya", "Nairobi"},
        {"Ethiopia", "Addis Ababa"},
        {"Venezuela", "Caracas"},
        {"Cuba", "Havana"},
        {"Jamaica", "Kingston"},
        {"Haiti", "Port-au-Prince"},
        {"Panama", "Panama City"},
        {"Costa Rica", "San José"}};
}
